### ISSUE TITLE
ValueError: not enough values to unpack (expected 16, got 10)

### ISSUE THREAD

**Issue by maguro27** [minar09/ACGPN#13]
Thank you for your great job!
However, the training script of this repository does not work.
I meet the ValueError when run `python train.py`.
In line 161 of the train.py,

> ValueError: not enough values to unpack (expected 16, got 10)

I checked the `models/pix2pixHD_model.py`.
Thus, the forward function of pix2pixHD_model.py returns only 10 arguments.
Now, I confirm the Unet class of the `models/networks.py` does not return `rx`, `ry`, `cx`, and `cy` arguments.
After that, I add the `rx`, `ry`, `cx`, and `cy` arguments to the `return` function of the forward function of the Unet class.

However, I cannot find `refined`, `rg`, and `cg` arguments of line 161 of the train.py.

Please fix the training scripts so it works.
Thanks.

**Comment by minar09** [comment]
Hi, @maguro27 , thanks for your comment. However, I am sorry to let you know that I have only tested and modified the testing script. The training scripting was copied as it is from the original repository and I did not run it. For more details, I'd recommend you refer to the repository from the original authors.

**Comment by joshchang0111** [comment]
Hi @maguro27 , have you fixed this problem? I'm running into the same issue. Looking forward to your response, thanks!

**Comment by arink20** [comment]
> Thank you for your great job! However, the training script of this repository does not work. I meet the ValueError when run `python train.py`. In line 161 of the train.py,
> 
> > ValueError: not enough values to unpack (expected 16, got 10)
> 
> I checked the `models/pix2pixHD_model.py`. Thus, the forward function of pix2pixHD_model.py returns only 10 arguments. Now, I confirm the Unet class of the `models/networks.py` does not return `rx`, `ry`, `cx`, and `cy` arguments. After that, I add the `rx`, `ry`, `cx`, and `cy` arguments to the `return` function of the forward function of the Unet class.
> 
> However, I cannot find `refined`, `rg`, and `cg` arguments of line 161 of the train.py.
> 
> Please fix the training scripts so it works. Thanks.

@maguro27 can i see your networks.py , train.py and how did u change it to get rx,ry,cx,cy,rg,cg ?
