### ISSUE TITLE
How to test with custom image ?

### ISSUE THREAD

**Issue by josearangos** [minar09/ACGPN#3]
Thank you very much for contributing to this amazing project.

I am trying to test the model with custom images and I have:
  - test_color
  - test_edge
  - test_img
  - test_label
  - test_pose

How can you generate the files from the folders ?:
  - test_mask
  - tes_colormask

Thanks

**Comment by minar09** [comment]
Hi @josearangos , thanks for your kind words. I haven't tried on the custom images yet, however, test_mask and test_colormask seem to be random black and white lines/shapes. Maybe you can simply make some and use for all your custom images. Sorry that couldn't help much.

**Comment by joel1895** [comment]
There is no need to fill anything in the test_mask and test_colomask folder, just create it as a dummy folder for the sake of completion . Even if its empty, it won't throw any error nor it will affect the end result

**Comment by josearangos** [comment]
Thanks, this is my results

![image](https://user-images.githubusercontent.com/13352055/95605437-95981200-0a1e-11eb-80c9-2682cecfe272.png)
![image](https://user-images.githubusercontent.com/13352055/95605449-98930280-0a1e-11eb-986e-4eb3c94d0857.png)
![image](https://user-images.githubusercontent.com/13352055/95605468-9cbf2000-0a1e-11eb-9733-9e4bdbd71d2a.png)
![image](https://user-images.githubusercontent.com/13352055/95605479-a052a700-0a1e-11eb-8497-2950d6621156.png)
![image](https://user-images.githubusercontent.com/13352055/95605492-a47ec480-0a1e-11eb-9956-7ca00f19040b.png)
![image](https://user-images.githubusercontent.com/13352055/95605502-a9dc0f00-0a1e-11eb-873f-7dc23c81eade.png)
![image](https://user-images.githubusercontent.com/13352055/95605527-b2344a00-0a1e-11eb-960b-7bd49678f51e.png)
![image](https://user-images.githubusercontent.com/13352055/95605538-b82a2b00-0a1e-11eb-8416-a4e6ea615cac.png)

**Comment by AyeshaShafique** [comment]
hi, 

can anyone help me , how to setup this project on windows for the testng purpose, pls?

**Comment by XYHu122** [comment]
> Thanks, this is my results
> 
> ![image](https://user-images.githubusercontent.com/13352055/95605437-95981200-0a1e-11eb-80c9-2682cecfe272.png)
> ![image](https://user-images.githubusercontent.com/13352055/95605449-98930280-0a1e-11eb-986e-4eb3c94d0857.png)
> ![image](https://user-images.githubusercontent.com/13352055/95605468-9cbf2000-0a1e-11eb-9733-9e4bdbd71d2a.png)
> ![image](https://user-images.githubusercontent.com/13352055/95605479-a052a700-0a1e-11eb-8497-2950d6621156.png)
> ![image](https://user-images.githubusercontent.com/13352055/95605492-a47ec480-0a1e-11eb-9956-7ca00f19040b.png)
> ![image](https://user-images.githubusercontent.com/13352055/95605502-a9dc0f00-0a1e-11eb-873f-7dc23c81eade.png)
> ![image](https://user-images.githubusercontent.com/13352055/95605527-b2344a00-0a1e-11eb-960b-7bd49678f51e.png)
> ![image](https://user-images.githubusercontent.com/13352055/95605538-b82a2b00-0a1e-11eb-8416-a4e6ea615cac.png)

Hi, I'm also trying to use my custom images to test the model, but I don't know how to generate test_label and test_pose of my own images. 
I saw your very successful test results, so I want to know how you did it, could you please give me some advice? Thanks a lot!

**Comment by minar09** [comment]
> hi,
> 
> can anyone help me , how to setup this project on windows for the testng purpose, pls?

Hi @AyeshaShafique , I have tested this repository on a windows pc as well and it works. Please go ahead with the requirements and installation. Good luck!

**Comment by hrushikesh26** [comment]
> > Thanks, this is my results
> > ![image](https://user-images.githubusercontent.com/13352055/95605437-95981200-0a1e-11eb-80c9-2682cecfe272.png)
> > ![image](https://user-images.githubusercontent.com/13352055/95605449-98930280-0a1e-11eb-986e-4eb3c94d0857.png)
> > ![image](https://user-images.githubusercontent.com/13352055/95605468-9cbf2000-0a1e-11eb-9733-9e4bdbd71d2a.png)
> > ![image](https://user-images.githubusercontent.com/13352055/95605479-a052a700-0a1e-11eb-8497-2950d6621156.png)
> > ![image](https://user-images.githubusercontent.com/13352055/95605492-a47ec480-0a1e-11eb-9956-7ca00f19040b.png)
> > ![image](https://user-images.githubusercontent.com/13352055/95605502-a9dc0f00-0a1e-11eb-873f-7dc23c81eade.png)
> > ![image](https://user-images.githubusercontent.com/13352055/95605527-b2344a00-0a1e-11eb-960b-7bd49678f51e.png)
> > ![image](https://user-images.githubusercontent.com/13352055/95605538-b82a2b00-0a1e-11eb-8416-a4e6ea615cac.png)
> 
> Hi, I'm also trying to use my custom images to test the model, but I don't know how to generate test_label and test_pose of my own images.
> I saw your very successful test results, so I want to know how you did it, could you please give me some advice? Thanks a lot!

Hey @ahchchchc Did you found out how to do this? I am also looking for solution to this. I would also like to know how to generate test_edge. Its kind of urgent so can anyone help please?
