### ISSUE TITLE
Using Multiple GPUs

### ISSUE THREAD

**Issue by hfarhidzadeh** [minar09/ACGPN#7]
Hi,

Can you let me know how to use mutilGPU on this code? I checked netwoeks.py, all networks are assigned to `model.cuda(gpus_id[0])`. By` model.cuda(gpus_id)`, does the network works on gpus or I need to do 

`model = nn.DataParallel(model)`  as well?

**Comment by minar09** [comment]
Hi @hfarhidzadeh , I think you can just specify the number of GPUs in the base_options.py arguments, and it should work fine. See here: https://github.com/minar09/ACGPN/blob/c4df9738e13412f9fb2be57deefcce99373fa5f1/options/base_options.py#L16
